apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mlflow.name }}
  labels:
    app: {{ .Values.mlflow.appLabel }}
spec:
  replicas: {{ .Values.mlflow.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.mlflow.appLabel }}

  template:
    metadata:
      labels:
        app: {{ .Values.mlflow.appLabel }}

    spec:
      securityContext:
        fsGroup: {{ .Values.security.fsGroup }}

      containers:
        - name: {{ .Values.mlflow.containerName }}
          image: {{ .Values.mlflow.image }}

          securityContext:
            runAsUser: {{ .Values.security.runAsUser }}
            runAsGroup: {{ .Values.security.runAsGroup }}

          ports:
            - containerPort: {{ .Values.mlflow.port }}

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.usernameKey }}

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.passwordKey }}

            - name: MLFLOW_TRACKING_URI
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}

          command:
            - mlflow
            - server
            - --backend-store-uri
            - postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}
            - --artifacts-destination
            - {{ .Values.mlflow.artifactPath }}
            - --serve-artifacts
            - --host
            - {{ .Values.mlflow.host }}
            - --port
            - "{{ .Values.mlflow.port }}"
            - --allowed-hosts
            - "{{ .Values.mlflow.allowedHosts }}"
            - --cors-allowed-origins
            - "{{ .Values.mlflow.corsOrigins }}"

          volumeMounts:
            - name: mlflow-artifacts
              mountPath: {{ .Values.mlflow.artifactPath }}

      volumes:
        - name: mlflow-artifacts
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.mlflow.appLabel }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.mlflow.port }}

